name: login
description: a simple login app with package authentication_repository
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  authentication_repository: 
    path: ./packages/authentication_repository
  user_repository:
    path: ./packages/user_repository
  flutter_bloc: ^8.1.3
  formz: ^0.6.0
  equatable: ^2.0.5
  google_fonts: ^6.0.0
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
